name: socigate_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  delayed_display: ^2.0.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.5
  retrofit: ^4.4.1
  rive: ^0.13.20
  toastification: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  assets:
    - shorebird.yaml
    - assets/logo/png/
    - assets/images/
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Black.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Bold.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-ExtraBold.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-ExtraLight.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Light.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Medium.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Regular.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-SemiBold.ttf
        - asset: fonts/montserrat/ArbFONTS-Montserrat-Arabic-Thin.ttf
